# Replace the text below to customize your site
site_name: Marcel Bentancor - UTEC & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Marcel Bentancor
copyright: Copyleft 2024 Marcel Bentancor" - GNU Free Documentation License
repo_name: 'Name : Repositorio de EFDI de Marcel Bentancor'
site_url: https://marcelbentancor.github.io/marcel_bentancor/
repo_url: https://github.com/marcelbentancor/marcel_bentancor.git


nav:
  - Home: index.md
  - About: about/me.md
  - Modulos Técnicos :
    - MT01: tecnicos/mt01.md
    - MT02: tecnicos/mt02.md
    - MT03: tecnicos/mt03.md
    - MT04: tecnicos/mt04.md
    - MT05: tecnicos/mt05.md
    - MT08: tecnicos/mt08.md
  - Modulos Diseño :
    - MD01: diseno/md01.md
    - MD02: diseno/md02.md
  - Modulos Innovación :
    - MI01: innovacion/mi01.md
    - MI03: innovacion/mi03.md
  - Proyecto Integrador:
    - Ideas Iniciales: proyecto/proyecto.md


extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/marceluy/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dounmonton
    - icon: fontawesome/brands/github
      link: "https://github.com/marcelbentancor/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: #0277BD
    accent: purple
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
